from typing import Any

class TextSanitizer:
    def __init__(self, profile: str = ..., **kwargs: Any) -> None: ...
    def scan(self, content: str) -> dict[str, Any]: ...
    def sanitize(self, text: str) -> str: ...
    def sanitize_with_scope(self, content: str) -> tuple[str, dict[str, int]]: ...
    def deanonymize(
        self,
        text: str,
        policy: str = ...,
        token_scope: dict[str, int] | None = ...,
    ) -> str: ...
